// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApp.Data.Concrete;

#nullable disable

namespace StoreApp.Web.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("StoreApp.Data.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Telefon",
                            Description = "Cox gozel telefon",
                            Name = "Samsung S24",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Telefon",
                            Description = "Cox gozel telefon",
                            Name = "Samsung S25",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Telefon",
                            Description = "Cox gozel telefon",
                            Name = "Samsung S26",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Telefon",
                            Description = "Cox gozel telefon",
                            Name = "IPhone 11 pro",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Telefon",
                            Description = "Cox gozel telefon",
                            Name = "IPhone 12 pro Max",
                            Price = 2800m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Telefon",
                            Description = "Cox serfeli telefon",
                            Name = "IPhone 15 pro Max",
                            Price = 3800m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
